version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: hackathon_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon_mvp
    ports:
      - "5433:5432"  # Maps host 5433 to container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
